from __future__ import annotations

from enum import Enum
from typing import Any

from .base import CamelModel


class ErrorCode(str, Enum):
    UNSUPPORTED_FILE_TYPE = "UNSUPPORTED_FILE_TYPE"
    INVALID_IMAGE = "INVALID_IMAGE"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    CORRUPTED_PDF = "CORRUPTED_PDF"
    PASSWORD_PROTECTED_PDF = "PASSWORD_PROTECTED_PDF"
    TOO_MANY_PAGES = "TOO_MANY_PAGES"
    UPLOAD_FAILED = "UPLOAD_FAILED"
    JOB_NOT_FOUND = "JOB_NOT_FOUND"
    JOB_ALREADY_PROCESSING = "JOB_ALREADY_PROCESSING"
    DOCUMENT_NOT_READY = "DOCUMENT_NOT_READY"
    RECONSTRUCTION_FAILED = "RECONSTRUCTION_FAILED"
    INVALID_EXPORT_FORMAT = "INVALID_EXPORT_FORMAT"
    INVALID_DOCUMENT_CONTENT = "INVALID_DOCUMENT_CONTENT"
    EXPORT_FAILED = "EXPORT_FAILED"
    EXPORT_TIMEOUT = "EXPORT_TIMEOUT"
    PROCESSING_FAILED = "PROCESSING_FAILED"
    OCR_FAILED = "OCR_FAILED"
    LAYOUT_ANALYSIS_FAILED = "LAYOUT_ANALYSIS_FAILED"
    READING_ORDER_FAILED = "READING_ORDER_FAILED"


class ErrorObject(CamelModel):
    code: ErrorCode
    message: str
    user_message: str
    retryable: bool
    details: dict[str, Any] | None = None
